name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Environment (Using NodeJS 12.x)
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Run unit tests and collect coverage
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v1
      - name: Build
        with:
           VUE_APP_GH_TOKEN: ${{ tokens.VUE_APP_GH_TOKEN }}
        run: npm run build

      - uses: netlify/actions/cli@master
      - name: Deploy to Netlify
        run: npm --version