name: Continuous Integration

on:
  push:
    branches:
      - 'master'

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment and installing dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - shell: bash
        run: npm install

      - name: 'Uploading node_modules'
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules

  testing:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run unit tests and collect coverage
        uses: actions/download-artifact@v1
        with:
          name: node_modules
      - shell: bash
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: Build application
      - uses: actions/download-artifact@v1
        with:
          name: node_modules
      - shell: bash
        run: npm run build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # - uses: actions/download-artifact@v1
      #   with:
      #     name: node_modules
      - name: Deploy to Netlify
      - shell: bash
        run: npm --version
        # uses: actions/upload-artifact@v1
        # with:
        #   name: dist
        #   path: dist
