name: Continuous Integration

on:
  push:
    branches:
      - 'master'

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment and installing dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - shell: bash
        run: |
          npm run test:unit
          npm run build
      - name: Upload dist folder
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    steps:
      - name: Deploy to Netlify
        uses: actions/download-artifact@v1
        with:
          name: dist

      - shell: bash
        run: npm --version
        # uses: actions/upload-artifact@v1
        # with:
        #   name: dist
        #   path: dist
