name: Continuous Integration

on:
  push:
    branches:
      - 'master'

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Environment (Using NodeJS 12.x)
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Run unit tests and collect coverage
        run: npm run test:unit

      - name: Build Application
        env:
          VUE_APP_GH_TOKEN: ${{ secrets.VUE_APP_GH_TOKEN }}
        run: npm run build

      - name: Upload distribution folder
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    steps:
      - name: Download distribution folder
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npm install netlify-cli
          npx netlify deploy --dir=dist --prod
