name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup Node environment (12.x)
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
  
    - name: install dependencies and run unit tests
      run: |
        npm install
        npm run test:unit
